window.RESTAURANTS = [
  {
    "name": "Al Halal Zaiqa",
    "subtitle": "The Loop",
    "address": "449 W North Ave, Chicago, IL 60610",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-1.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Al Kabeer Restaurant",
    "subtitle": "West Ridge",
    "address": "6426 N Western Ave, Chicago, IL 60645",
    "badge": "Not Renewed",
    "badgeClass": "status-note",
    "image": "assets/card-2.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJm3fJN4zRD4gRHkjQbf-YoQs",
    "googleMapsUri": "https://maps.google.com/?cid=838119228494071838&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Al Safa (Restaurant)",
    "subtitle": "West Ridge",
    "address": "3146 W Touhy Ave, Chicago, IL 60645",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-3.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Al Yemen Al Saeed",
    "subtitle": "West Ridge",
    "address": "3456 W. Foster Ave, Chicago, IL 60625",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-1.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJe0IOdubND4gRUMlFK1R2-GI",
    "googleMapsUri": "https://maps.google.com/?cid=7131580113816504656&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Ali Nihari",
    "subtitle": "Devon Avenue",
    "address": "2548 W Devon Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-2.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Bar.B.Q Tonight",
    "subtitle": "Devon Avenue",
    "address": "2525 W Devon Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-3.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJP7FFFQDRD4gR_AK8KbA3A0Q",
    "googleMapsUri": "https://maps.google.com/?cid=4900822049263190780&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Bundoo Khan Restaurant",
    "subtitle": "Devon Avenue",
    "address": "2539 W. Devon Ave., Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-1.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Burger Zone",
    "subtitle": "West Ridge",
    "address": "3332 W Foster Ave, Chicago, IL 60625",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-2.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJn45juYHND4gRTWJDD9EZwD0",
    "googleMapsUri": "https://maps.google.com/?cid=4449584817536983629&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Byrd's Hot Chicken Chicago",
    "subtitle": "The Loop",
    "address": "2634 N Clark St, Chicago, IL 60614",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-3.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Byrd's Hot Chicken Union Station",
    "subtitle": "Chicago",
    "address": "319 S Jefferson St, Chicago, IL 60661",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-1.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Chi Tea",
    "subtitle": "Rogers Park",
    "address": "6474 N Sheridan Rd, Chicago, IL 60626",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-2.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Dastarkhwan",
    "subtitle": "West Ridge",
    "address": "6418 N Western Ave, Chicago, IL 60645",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-3.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJ6_lgtAnRD4gRexfcTVaoamU",
    "googleMapsUri": "https://maps.google.com/?cid=7307838433988974459&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Delhi Darbar",
    "subtitle": "Devon Avenue",
    "address": "3010 W Devon Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-1.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Drippin Bites",
    "subtitle": "Rogers Park",
    "address": "6808 N Sheridan Rd, Chicago, IL 60626",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-2.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJ5Y_nVrHRD4gR4kdKnPCvFjI",
    "googleMapsUri": "https://maps.google.com/?cid=3609265599333156834&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Firebird Piri Piri Grill",
    "subtitle": "Uptown",
    "address": "4546 N Magnolia Ave, Chicago, IL 60640",
    "badge": "Not Renewed",
    "badgeClass": "status-note",
    "image": "assets/card-3.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Flamin Bites",
    "subtitle": "Lakeview",
    "address": "2814 N Halsted St, Chicago, IL 60657",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-1.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Fried Junction",
    "subtitle": "West Ridge",
    "address": "6349 N Claremont Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-2.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJPwlj_rXRD4gRGnfR98PBDHA",
    "googleMapsUri": "https://maps.google.com/?cid=8074041279388940058&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Ghareeb Nawaz Restaurant",
    "subtitle": "Devon Avenue",
    "address": "2032 W Devon Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-3.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJ855DdcHRD4gRo6iEljO2bUc",
    "googleMapsUri": "https://maps.google.com/?cid=5146970281839208611&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Ghareeb Nawaz UIC",
    "subtitle": "University Village",
    "address": "807 W Roosevelt Rd, Chicago, IL 60608",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-1.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJQ5WH6-8sDogRiOSiAaMLbus",
    "googleMapsUri": "https://maps.google.com/?cid=16964509641086264456&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Hadramout Restaurant & Bakery",
    "subtitle": "Devon Avenue",
    "address": "3100 W Devon Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-2.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Halal Food Studio",
    "subtitle": "Chicago",
    "address": "6405 N Bell Ave, Chicago, IL 60645",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-3.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJWwDmHwzRD4gRXMMk_5VgbmM",
    "googleMapsUri": "https://maps.google.com/?cid=7164770254540030812&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Halal Smash Burger & Phillies",
    "subtitle": "West Ridge",
    "address": "5019 N. Western Ave, Chicago, IL 60625",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-1.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Halal Smash Burger & Phillies",
    "subtitle": "West Ridge",
    "address": "6404 N. California Ave, Chicago, IL 60645",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-2.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Halaleez NY Chicken & Gyro Rice Bowls",
    "subtitle": "The Loop",
    "address": "400 S Financial Pl, Chicago, IL 60605",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-3.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "House of Biryani",
    "subtitle": "Devon Avenue",
    "address": "2306 W Devon Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-1.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJ-VLLABrRD4gR323fqUjmwxE",
    "googleMapsUri": "https://maps.google.com/?cid=1280119918865378783&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Hyderabad House Devon",
    "subtitle": "Devon Avenue",
    "address": "2225 W. Devon Ave., Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-2.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Hyderabad Kitchen",
    "subtitle": "West Ridge",
    "address": "6242-44 N California Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-3.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Indian Street Food by Tawakkul",
    "subtitle": "Devon Avenue",
    "address": "2437 W Devon Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-1.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJX0qi0KLRD4gRerC_FTFF2CM",
    "googleMapsUri": "https://maps.google.com/?cid=2582890463417577594&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "JK Kabab Express (Devon)",
    "subtitle": "Devon Avenue",
    "address": "2510 W Devon Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-2.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Kabab King Grill",
    "subtitle": "Devon Avenue",
    "address": "2305 W. Devon Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-3.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Khan BBQ",
    "subtitle": "Devon Avenue",
    "address": "2401 W Devon Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-1.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Mintza",
    "subtitle": "Devon Avenue",
    "address": "2245 W Devon Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-2.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Nawaz Gulshan",
    "subtitle": "West Ridge",
    "address": "6237 N Western Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-3.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJhZQn4NDRD4gRVY2nw9VgOlg",
    "googleMapsUri": "https://maps.google.com/?cid=6357500295213714773&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "New Naan on Devon",
    "subtitle": "Devon Avenue",
    "address": "2241 W. Devon Ave., Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-1.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "New Zaiqa",
    "subtitle": "The Loop",
    "address": "1316 N Clybourn Ave, Chicago, IL 60610",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-2.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJIbkvjGbTD4gRwyg2Bgec16k",
    "googleMapsUri": "https://maps.google.com/?cid=12238422066385529027&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "NYC Halal Eats",
    "subtitle": "Devon Avenue",
    "address": "2657 W Devon Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-3.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJiyZdpj3RD4gRXDjd-2MLsmk",
    "googleMapsUri": "https://maps.google.com/?cid=7616162443892176988&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Pak Sweets on Devon",
    "subtitle": "Devon Avenue",
    "address": "2326 W Devon Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-1.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Pita Pita Mediterranean Grill",
    "subtitle": "The Loop",
    "address": "200 W Randolph St, Chicago, IL 60606",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-2.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJseo9ZbMtDogR_tiNgwplyoY",
    "googleMapsUri": "https://maps.google.com/?cid=9712686642209085694&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Pita Pita Mediterranean Grill",
    "subtitle": "Near West Side",
    "address": "705 S Seeley Ave, Chicago, IL 60612",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-3.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJr7o_p-EtDogR1k5B-bf-Tn8",
    "googleMapsUri": "https://maps.google.com/?cid=9173549557114556118&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Rickshaw Pakistani & Indian Street Eats",
    "subtitle": "Irving Park",
    "address": "4304 N Pulaski Rd, Chicago, IL 60641",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-1.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJF7U3i7PND4gRVMNmaqGucOw",
    "googleMapsUri": "https://maps.google.com/?cid=17037309398640673620&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Ruman Chai Shai & Restaurant",
    "subtitle": "West Ridge",
    "address": "6348 N Artesian Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-2.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Sabri Nihari",
    "subtitle": "Devon Avenue",
    "address": "2502 W Devon Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-3.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Saffron & Salsa",
    "subtitle": "West Ridge",
    "address": "3605 N Western Ave, Chicago, IL 60618",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-1.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJCYiUgfjTD4gRcPXrNSrd7tA",
    "googleMapsUri": "https://maps.google.com/?cid=15055213777709167984&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "SALT burgers + fries",
    "subtitle": "The Loop",
    "address": "1920 W North Ave, Chicago, IL 60622",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-2.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJRWtUROzTD4gRtQh9dcEbKLI",
    "googleMapsUri": "https://maps.google.com/?cid=12837541255533365429&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "SALT burgers + fries",
    "subtitle": "Rogers Park",
    "address": "6558 N Sheridan Rd, Chicago, IL 60626",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-3.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJx4QCltbRD4gRu-QaEh2oriw",
    "googleMapsUri": "https://maps.google.com/?cid=3219695626427753659&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Serena Restaurant",
    "subtitle": "Devon Avenue",
    "address": "2536 W Devon Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-1.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJlfzvLd3RD4gR-b0cL6G6U5o",
    "googleMapsUri": "https://maps.google.com/?cid=11120437106350800377&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Tabaq Restaurant",
    "subtitle": "The Loop",
    "address": "1245 N. Clybourn Ave, Chicago, IL 60610",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-2.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJd5wenTfTD4gR12h2iKWrxwc",
    "googleMapsUri": "https://maps.google.com/?cid=560605406078331095&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Tanoor Kabob",
    "subtitle": "South Lawndale",
    "address": "2304 S Kedzie Ave, Chicago, IL 60623",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-3.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJ91FeqrQtDogRTx5j_3nDTUg",
    "googleMapsUri": "https://maps.google.com/?cid=5210035272680676943&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Tawakkul Restaurant",
    "subtitle": "West Ridge",
    "address": "6410 N. Claremont Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-1.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "Thali Corner",
    "subtitle": "Devon Avenue",
    "address": "2350 W. Devon Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-2.png",
    "imageAlt": "",
    "googlePlaceId": "",
    "googleMapsUri": ""
  },
  {
    "name": "The Halal Burger",
    "subtitle": "West Ridge",
    "address": "6234 N California Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-3.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJg0P2nR_OD4gRmp-k8AOMc7U",
    "googleMapsUri": "https://maps.google.com/?cid=13074948091736792986&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Tim Tim's Halal Grill",
    "subtitle": "Irving Park",
    "address": "4148 W MONTROSE AVE, Chicago, IL 60641",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-1.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJvYTouTrND4gRuccr5Ls5QfE",
    "googleMapsUri": "https://maps.google.com/?cid=17384239515776567225&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Usmania Chinese Restaurant",
    "subtitle": "Devon Avenue",
    "address": "2253 W Devon Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-2.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJC-gL2sLRD4gRirqqczWhjDQ",
    "googleMapsUri": "https://maps.google.com/?cid=3786578637657651850&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  },
  {
    "name": "Usmania Fine Dining",
    "subtitle": "Devon Avenue",
    "address": "2244 W Devon Ave, Chicago, IL 60659",
    "badge": "Zabihah Halal",
    "badgeClass": "",
    "image": "assets/card-3.png",
    "imageAlt": "",
    "googlePlaceId": "ChIJsXGF2MLRD4gRAnhcpO-Mu0w",
    "googleMapsUri": "https://maps.google.com/?cid=5529167928410011650&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA"
  }
];
